# DNS协议细节再此处 https://www.iana.org/assignments/dns-parameters/dns-parameters.xhtml

log:
  level: info # 日志级别。可选 "debug" "info" "warn" "error"。默认 "info"。
  production: false

plugins:
  # 规则导入
  - tag: "domainDirect"
    type: "domain_set"
    args:
      files:
        - "../rule_data/v2ray-rules-dat/direct-list.txt"
        - "../rule_data/v2ray-rules-dat/china-list.txt"
        - "../rule_data/v2ray-rules-dat/apple-cn.txt"
        - "../rule_data/v2ray-rules-dat/google-cn.txt"
        - "../rule_data/domain-list-custom/cn.txt"
        - "../rule_data/domain-list-custom/geolocation-cn.txt"
        - "../rule_data/domain-list-custom/tld-cn.txt"

  - tag: "domainProxy"
    type: "domain_set"
    args:
      files:
        - "../rule_data/v2ray-rules-dat/proxy-list.txt"
        - "../rule_data/v2ray-rules-dat/gfw.txt"
        - "../rule_data/v2ray-rules-dat/greatfire.txt"
        - "../rule_data/domain-list-custom/geolocation-!cn.txt"
        - "../rule_data/domain-list-custom/tld-!cn.txt"

  - tag: "domainReject"
    type: "domain_set"
    args:
      files:
        - "../rule_data/v2ray-rules-dat/reject-list.txt"
        - "../rule_data/domain-list-custom/category-ads-all.txt"
        - "../rule_data/domain-list-custom/private.txt"

  - tag: "ipDirect"
    type: "ip_set"
    args:
      files:
        - "../rule_data/geoip/text/cn.txt"

  # 转发设置
  - tag: "forwardDirect"
    type: "forward"
    args:
      upstreams:
        addr: "udp://127.0.0.1:8153"

  - tag: "forwardProxy"
    type: "forward"
    args:
      upstreams:
        addr: "udp://127.0.0.1:8253"

  - tag: "forwardBackup"
    type: "forward"
    args:
      upstreams:
        addr: "udp://127.0.0.1:8353"

  # 回落查询
  - tag: "fallbackDrop"
    type: "sequence"
    args:
      - exec: drop_resp
      - matches: mark 1111
        exec: query_summary fallbackDrop

  - tag: "fallbackCacheSet"
    type: "sequence"
    args:
      - matches: mark 1111
        exec: query_summary TryCacheSet

      - matches:
          - mark 2222 # 仅针对ip地址查询
          - has_wanted_ans
        exec: cache 65535
      - matches:
          - mark 1111
          - has_wanted_ans
        exec: query_summary fallbackCacheSet

  - tag: "fallbackCacheGet"
    type: "sequence"
    args:
      - matches: mark 1111
        exec: query_summary TryCacheGet

      - matches: mark 2222 # 仅针对ip地址查询
        exec: cache 65535
      - matches:
          - mark 1111
          - has_resp
        exec: query_summary fallbackCacheGet

  - tag: "fallbackCache"
    type: "sequence"
    args:
      - matches: mark 655351
        exec: jump fallbackCacheSet
      - matches: mark 655351
        exec: return

      - matches: mark 655350
        exec: jump fallbackCacheGet
      - matches: mark 655350
        exec: return

  - tag: "fallbackDirect"
    type: "sequence"
    args:
      - exec: $forwardDirect # 使用国内DOH

  - tag: "fallbackProxy"
    type: "sequence"
    args:
      - exec: $forwardProxy # 使用国际加密
      - matches:
          - mark 8153
          - mark 2222 # 仅针对ip地址查询
          - has_wanted_ans
          - "!resp_ip $ipDirect" #强制要求国内IP
        exec: jump fallbackDrop

  - tag: "fallbackBackup"
    type: "sequence"
    args:
      - matches: mark 1111
        exec: query_summary fallbackBackup

      - exec: $forwardBackup # 使用国际DOH
      - matches: has_wanted_ans
        exec: mark 655351 # 标记写入cache
      - exec: jump fallbackCache

  - tag: "fallbackPrimary"
    type: "sequence"
    args:
      - matches: mark 1111
        exec: query_summary fallbackPrimary

      - exec: mark 655350 # 标记获取cache
      - exec: jump fallbackCache
      - matches: has_resp
        exec: accept

      - exec: mark 8153 # 8153标记不在所有规则中的，优先查询国内IP
      - exec: jump fallbackProxy
      - matches: "!has_wanted_ans"
        exec: jump fallbackBackup

  - tag: "fallbackSecondary"
    type: "sequence"
    args:
      - matches: mark 1111
        exec: query_summary fallbackSecondary
      - exec: jump fallbackDirect

  - tag: "fallbackEntry"
    type: "fallback"
    args:
      primary: fallbackPrimary
      secondary: fallbackSecondary
      threshold: 700
      always_standby: false

  # 处理过程
  - tag: "processDirect"
    type: "sequence"
    args:
      - matches: mark 1111
        exec: query_summary processDirect
      - exec: jump fallbackDirect

  - tag: "processProxy"
    type: "sequence"
    args:
      - matches: mark 1111
        exec: query_summary processProxy
      - exec: jump fallbackProxy

  - tag: "processReject"
    type: "sequence"
    args:
      - matches: mark 1111
        exec: query_summary processReject
      - exec: reject 3

  - tag: "processEntry"
    type: "sequence"
    args:
      - exec: prefer_ipv4 # ipv4 优先
      - exec: mark 1111 # 控制 log 启用

      # 方便调试时分辨查询起始位置
      - matches: mark 1111
        exec: query_summary ------------

      # 2222 标记当前是 A/AAAA 这样的IP地址查询
      # 4444/6666 分别标记 ipv4/ipv6 查询
      - matches: qtype 1
        exec: mark 2222 4444
      - matches: qtype 28
        exec: mark 2222 6666

      # 优先阻止广告查询
      - matches: qname $domainReject
        exec: goto processReject

      # 直接国内查询
      - matches: qname $domainDirect
        exec: goto processDirect

      # 直接国际查询
      - matches: qname $domainProxy
        exec: goto processProxy

      # 不在规则中处理，则优先国内IP
      - exec: $fallbackEntry

  # 服务入口
  - tag: ""
    type: "udp_server"
    args:
      entry: "processEntry"
      listen: 0.0.0.0:8053
